pipeline {
  agent {
    docker { image 'node:16-alpine' } //configuring docker as agent
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'  //verifing container has nodejs
      }
    }
  }
}
